language: bash
services: docker

#install:
#  - git clone -v https://github.com/vertexproject/synapse.git /tmp/synapse

script:
  - docker build -f ./python36/Dockerfile ./python36 | tee build_log.txt
  - export IMAGE_ID=`grep "Successfully built" build_log.txt | grep -v "msgpack" | cut -f 3 -d " "`
  - docker run --rm $IMAGE_ID python -c "import msgpack; print(msgpack)"
  - docker run --rm $IMAGE_ID python -c "import tornado; print(tornado)"
  - docker run --rm $IMAGE_ID python -c "import psycopg2; print(psycopg2)"
  - docker run --rm $IMAGE_ID python -c "import paramiko; print(paramiko)"
  - docker run --rm $IMAGE_ID python -c "import cryptography; print(cryptography)"
  - docker run --rm $IMAGE_ID python -m pip freeze
  - python test/rewrite_dockerfile.py
  - docker build -f test/Dockerfile ./test | tee test_build_log.txt
  - export TEST_IMAGE_ID=`grep "Successfully built" test_build_log.txt | grep -v "msgpack" | cut -f 3 -d " "`
  - echo "Running tests from ${TEST_IMAGE_ID}"
  - docker-compose -f ./test/docker-compose.yml up -d
  - docker run --rm --network host -e "SYN_TEST_PG_DB=postgres:hehe@localhost:5432/syn_test" ${TEST_IMAGE_ID} 2>&1
  - docker-compose -f ./test/docker-compose.yml down