language: bash
services: docker

script:
  - docker build -t syntestimage:regular -f ./python36/Dockerfile . | tee build_log.txt
  - docker run --rm syntestimage:regular python -c "import msgpack; print(msgpack)"
  - docker run --rm syntestimage:regular python -c "import tornado; print(tornado)"
  - docker run --rm syntestimage:regular python -c "import psycopg2; print(psycopg2)"
  - docker run --rm syntestimage:regular python -m pip freeze
  - docker build -t syntestimage:test -f test/Dockerfile ./test | tee test_build_log.txt
  - echo "Running tests from syntestimage:test"
  - docker-compose -f ./test/docker-compose.yml up -d
  - docker run --rm --network host -e "SYN_TEST_PG_DB=postgres:hehe@localhost:5432/syn_test" syntestimage:test 2>&1
  - docker-compose -f ./test/docker-compose.yml down
